export const PollingErrors = {
  SYSTEM: {
    DATABASE: "ERROR.SYSTEM.DATABASE"
  },

  REGISTRATION: {
    USER_EMAIL_ALREADY_EXISTS   : "ERROR.REGISTRATION.USER_EMAIL_ALREADY_EXISTS",
    USER_HANDLE_ALREADY_EXISTS  : "ERROR.REGISTRATION.USER_HANDLE_ALREADY_EXISTS",
  },

  AUTH: {
    INVALID_CREDENTIALS   : "ERROR.AUTH.INVALID_CREDENTIALS",
    UNAUTHORIZED          : "ERROR.AUTH.UNAUTHORIZED",
  },

  GROUPS: {
    GROUP_HANDLE_ALREADY_EXISTS : "ERROR.GROUPS.GROUP_HANDLE_ALREADY_EXISTS",
    GROUP_DOES_NOT_EXIST        : "ERROR.GROUPS.GROUP_DOES_NOT_EXIST",
  }
};
